pipecat-ai/docs

README.md
Make the README standout re-using the logo and description from the main repo.
Add details on how to contribute and run mintlify locally to test changes.
=> feat: Update README with logo + instructions to contribute

architecture.mdx, mint.json, misc/metrics.mdx, misc/reporting.mdx
This section needs https://github.com/pipecat-ai/pipecat/pull/624 to be merged to be accurate! 😅 
(Also sneaking a couple typo fixes in Architecture.mdx)
(Also also the word _metrics_ looks _so weird_ now)
=> Adding Metrics docs

api-reference/frames/metrics.mdx, api-reference/pipelines/parallel-pipeline.mdx, api-reference/pipelines/pipeline.mdx, api-reference/pipelines/sync-parallel-pipeline.mdx, api-reference/processors/aggregators/sentence.mdx, api-reference/processors/aggregators/vision-image.mdx, api-reference/services/llm/anthropic.mdx, api-reference/services/llm/azure.mdx, api-reference/services/llm/fireworks.mdx, api-reference/services/llm/gemini.mdx, api-reference/services/llm/ollama.mdx, api-reference/services/llm/openai.mdx, api-reference/services/llm/openpipe.mdx, api-reference/services/llm/together.mdx
Some light cleanup for all LLMs:
- Make input params ParamFields (not just code)
-  Improve context management sections
- Some headings fixes
=> LLM docs fixes

api-reference/services/transport/daily.mdx
A more complete list of supported DailyTransport methods.
=> Add Daily methods docs

api-reference/services/base-service-classes.mdx, api-reference/services/transport/daily.mdx
- Adapt DailyParams to the Mintlify format. Be more explicit about VAD usage. Link to SileroVAD docs.
- Add TransportParams documentation to the base service class docs.
=> Update base transport and Daily transport docs

getting-started/installation.mdx
Resolving this issue: https://github.com/pipecat-ai/pipecat/issues/507.
=> Provide OS specific instructions for install

api-reference/services/supported-services.mdx, api-reference/services/tts/rime.mdx, mint.json
Adding docs for the new RimeHttpTTSService.
=> Add Rime TTS docs

api-reference/services/transport/daily.mdx
Some missing methods and callbacks... no longer missing.
=> More Daily Transport docs updates

api-reference/processors/filters/stt-mute.mdx, api-reference/processors/stt-mute.mdx, mint.json
Documenting this feature: https://github.com/pipecat-ai/pipecat/pull/716
Waiting for some details on the PR to settle before merging.
=> Add STTMuteProcessor docs

guides/pipecat-flows.mdx, mint.json
=> Fix broken image

api-reference/services/llm/nim.mdx, api-reference/services/supported-services.mdx, mint.json
Don't merge until this is merged: https://github.com/pipecat-ai/pipecat/pull/772.
=> Add docs for NVIDIA's NIM LLMs

mint.json, server/services/supported-services.mdx, server/services/video/simli.mdx
Reworking docs from https://github.com/pipecat-ai/docs/pull/41.
=> Add Simli docs

server/services/s2s/openai.mdx
Depends on: https://github.com/pipecat-ai/pipecat/pull/889
=> Add model to OpenAIRealtimeBetaLLMService docs

mint.json, server/utilities/transcript-processor.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/860
=> Add TranscriptProcessor docs

server/services/tts/elevenlabs.mdx
Depends on: https://github.com/pipecat-ai/pipecat/pull/893
=> Update ElevenLabs docs

server/services/tts/playht.mdx
Updating to match the service implementation.
=> Update PlayHT languages

client/react-native/api-reference.mdx, client/react-native/introduction.mdx
=> Improving React Native docs.

client/js/transports/gemini.mdx, client/js/transports/openai-webrtc.mdx, mint.json
A docs update to go with https://github.com/pipecat-ai/pipecat-client-web-transports/pull/6
=> Add docs for OpenAI WebRTC Transport

guides/features/pipecat-flows.mdx, server/utilities/flows/pipecat-flows.mdx
Docs for these changes: https://github.com/pipecat-ai/pipecat-flows/pull/68
=> Update Flows reference and guide

mint.json, server/services/supported-services.mdx, server/services/tts/aws.mdx, server/services/tts/azure.mdx, server/services/tts/cartesia.mdx, server/services/tts/deepgram.mdx, server/services/tts/fish.mdx, server/services/tts/google.mdx, server/services/tts/lmnt.mdx, server/services/tts/openai.mdx, server/services/tts/playht.mdx, server/services/tts/rime.mdx, server/services/tts/xtts.mdx
Depends on: https://github.com/pipecat-ai/pipecat/pull/899
=> Add Fish audio docs, clean up pipeline example for TTS services

client/ios/introduction.mdx, client/ios/transports/daily.mdx
Fixing iOS Docs to match the current API.
=> Fixing iOS Docs

server/utilities/daily/rest-helpers.mdx
Changes from https://github.com/pipecat-ai/pipecat/pull/939
=> Document new Daily helper room params

server/frameworks/rtvi/rtvi-processor.mdx
An omission that was pointed out in Discord: https://discord.com/channels/1239284677165056021/1239284677823565826/1327643421112008787
=> Add docs for register_action, register_service

mint.json, server/services/llm/deepseek.mdx, server/services/supported-services.mdx
Pending: https://github.com/pipecat-ai/pipecat/pull/969
=> Add DeepSeek docs

mint.json, server/services/llm/openrouter.mdx, server/services/supported-services.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/967
=> Add OpenRouter docs

client/ios/api-reference.mdx, client/ios/introduction.mdx, client/ios/transports/daily.mdx
Updating Pipecat docs to match the refactors to use PipecatClientIOS
=> Updating Pipecat docs to match the refactors to use PipecatClientIOS

mint.json, server/utilities/user-idle-processor.mdx
These were missing. Now they're not!
=> Add UserIdleProcessor docs

guides/features/krisp.mdx
Updating Krisp models recommendations.
=> Updating Krisp models recommendations.

guides/features/pipecat-flows.mdx, server/utilities/flows/pipecat-flows.mdx
Related to: https://github.com/pipecat-ai/pipecat-flows/pull/84
=> Update docs for transition_callback in functions, other cleanup

server/services/tts/cartesia.mdx
Docs update for: https://github.com/pipecat-ai/pipecat/pull/1079
=> Update default Cartesia model

server/utilities/daily/rest-helpers.mdx
Docs update for: https://github.com/pipecat-ai/pipecat/pull/1075
=> Update Daily REST helpers with token params

server/utilities/transcript-processor.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1046
=> Update TranscriptProcessor for latest changes

guides/features/pipecat-flows.mdx, server/utilities/flows/pipecat-flows.mdx
Docs for: https://github.com/pipecat-ai/pipecat-flows/pull/83
=> Update Flows docs on actions

guides/features/pipecat-flows.mdx, server/utilities/flows/pipecat-flows.mdx
Docs for: https://github.com/pipecat-ai/pipecat-flows/pull/88
=> Updates Flows docs for context strategies

server/utilities/flows/pipecat-flows.mdx
Docs for: https://github.com/pipecat-ai/pipecat-flows/pull/91
=> Add docs for Flows get_current_context

guides/features/pipecat-flows.mdx, server/utilities/flows/pipecat-flows.mdx
Docs for: https://github.com/pipecat-ai/pipecat-flows/pull/92
=> Update docs for the new results arg in the transition callback

mint.json, server/services/stt/assemblyai.mdx, server/services/stt/azure.mdx, server/services/stt/deepgram.mdx, server/services/stt/gladia.mdx, server/services/stt/openai.mdx, server/services/stt/whisper.mdx, server/services/supported-services.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1128
Plus a little cleanup.
=> Add docs for OpenAI Whisper

server/utilities/filters/stt-mute.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1176
=> Update STTMuteFilter docs to list stt_service param as deprecated

mint.json, server/services/llm/groq.mdx, server/services/stt/groq.mdx, server/services/supported-services.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1183
=> Groq STT docs, update Groq LLM docs

server/services/supported-services.mdx, server/services/tts/rime.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1163
=> Update Rime docs for RimeTTSService

guides/telephony/daily-webrtc.mdx, guides/telephony/twilio-daily-webrtc.mdx
Fixing the docs because we renamed the folder in pipecat examples
=> updating links to sample code

server/utilities/filters/stt-mute.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1208
=> Add docs for STTMuteStrategy: MUTE_UNTIL_FIRST_BOT_COMPLETE

server/utilities/observers/observer-pattern.mdx, server/utilities/observers/rtvi-observer.mdx
=> Remove duplicate observer titles

getting-started/core-concepts.mdx, server/services/llm/anthropic.mdx, server/services/llm/gemini.mdx, server/services/llm/ollama.mdx, server/services/llm/openai.mdx, server/services/stt/assemblyai.mdx, server/services/stt/azure.mdx, server/services/stt/deepgram.mdx, server/services/stt/gladia.mdx, server/services/stt/google.mdx, server/services/stt/groq.mdx, server/services/stt/openai.mdx, server/services/stt/whisper.mdx, server/services/transport/daily.mdx, server/services/tts/aws.mdx, server/services/tts/azure.mdx, server/services/tts/deepgram.mdx, server/services/tts/google.mdx, server/services/tts/lmnt.mdx, server/services/tts/openai.mdx, server/services/tts/xtts.mdx, server/services/video/simli.mdx
Reported in Discord. Fix service and pipeline inconsistent naming.
=> Fix tts_service typos, and other pipeline inconsistencies

server/services/llm/gemini.mdx
- Update default model
- Fix incorrect GoogleLLMContext information
- Add a search grounding section
=> Fix issues with GoogleLLMContext, add search grounding docs

server/services/llm/grok.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1286
=> Update GrokLLMService docs with the latest models

mint.json, server/services/stt/ultravox.mdx, server/services/supported-services.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1331
=> Add UltravoxSTTService docs

mint.json, server/utilities/filters/frame-filter.mdx, server/utilities/filters/function-filter.mdx, server/utilities/filters/identify-filter.mdx, server/utilities/filters/null-filter.mdx, server/utilities/filters/wake-check-filter.mdx, server/utilities/filters/wake-notifier-filter.mdx
Resolving: https://github.com/pipecat-ai/pipecat/issues/1255
=> Add filters documentation

server/services/tts/neuphonic.mdx
Related PR for code change: https://github.com/pipecat-ai/pipecat/pull/1390
=> Added 5 new languages for Neuphonic: FR, PT, RU, ZH, HI.

server/services/llm/openai.mdx, server/services/tts/openai.mdx
=> Improvement pass for OpenAI services

mint.json, server/services/supported-services.mdx, server/services/tts/deepgram.mdx, server/services/tts/groq.mdx, server/services/tts/neuphonic.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1453
=> Add GroqTTSService docs

guides/features/pipecat-flows.mdx, server/frameworks/flows/pipecat-flows.mdx
Dependent on https://github.com/pipecat-ai/pipecat-flows/pull/107 landing and being published first.
=> Update docs with function actions

guides/features/pipecat-flows.mdx, server/frameworks/flows/pipecat-flows.mdx
Docs for: https://github.com/pipecat-ai/pipecat-flows/pull/115
=> Add FlowsFunctionSchema docs

server/services/s2s/openai.mdx
Fixes https://github.com/pipecat-ai/pipecat/issues/1351
=> Fix: Correct the imports for the OpenAI Realtime docs

guides/features/pipecat-flows.mdx, server/frameworks/flows/pipecat-flows.mdx
Docs for: https://github.com/pipecat-ai/pipecat-flows/pull/106
=> Update docs with FunctionHandler changes

mint.json, server/services/memory/mem0.mdx, server/services/supported-services.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1388
=> Add docs for mem0

mint.json, server/services/llm/qwen.mdx, server/services/supported-services.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1478
=> Add QwenLLMService docs

server/services/transport/daily.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1203
=> Add docs for update_remote_participants

server/services/stt/gladia.mdx
Docs for:
- https://github.com/pipecat-ai/pipecat/pull/1469
- https://github.com/pipecat-ai/pipecat/pull/1496
- https://github.com/pipecat-ai/pipecat/pull/1497
=> Update GladiaSTTService docs

mint.json, server/base-classes/transport.mdx, server/utilities/smart-turn.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1592
=> Add smart turn detection docs

server/services/memory/mem0.mdx
Mentioned about the new changes: https://github.com/pipecat-ai/pipecat/pull/1678
=> Doc: Mem0 doc update

server/utilities/smart-turn.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1717
=> Add LocalSmartTurnAnalyzer docs

guides/deployment/cerebrium.mdx, guides/deployment/pattern.mdx, guides/features/gemini-multimodal-live.mdx, guides/features/krisp.mdx, guides/telephony/daily-webrtc.mdx, guides/telephony/twilio-daily-webrtc.mdx, server/base-classes/transport.mdx, server/introduction.mdx, server/services/analytics/canonical.mdx, server/services/analytics/sentry.mdx, server/services/transport/daily.mdx, server/services/transport/fastapi-websocket.mdx, server/services/transport/small-webrtc.mdx, server/services/transport/websocket-server.mdx, server/services/video/tavus.mdx, server/utilities/audio/koala-filter.mdx, server/utilities/audio/krisp-filter.mdx, server/utilities/audio/noisereduce-filter.mdx, server/utilities/audio/silero-vad-analyzer.mdx, server/utilities/serializers/telnyx.mdx, server/utilities/serializers/twilio.mdx, server/utilities/smart-turn.mdx, server/utilities/smart-turn/fal-smart-turn.mdx, server/utilities/smart-turn/local-coreml-smart-turn.mdx, server/utilities/smart-turn/smart-turn-overview.mdx
Aligning with the TransportParams coming in 0.0.66.
=> Update to align with TransportParams changes for audio_ and video_

mint.json, server/utilities/observers/debug-observer.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1768
=> Add docs for DebugLogObserver

mint.json, server/services/llm/aws.mdx, server/services/stt/aws.mdx, server/services/supported-services.mdx, server/services/tts/aws.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1753
=> Update docs for new AWS services

guides/features/pipecat-flows.mdx, server/frameworks/flows/pipecat-flows.mdx
Documents what's implemented in https://github.com/pipecat-ai/pipecat-flows/pull/133
=> Document `NodeConfig.respond_immediately`

mint.json, server/services/supported-services.mdx, server/services/tts/sarvam.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1872
=> Add docs for Sarvam TTS

mint.json, server/utilities/serializers/introduction.mdx, server/utilities/serializers/plivo.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/1878
=> Add PlivoFrameSerializer docs

server/services/tts/rime.mdx
Updating for Language changes and a bunch of other things that were out of date.
=> Updated Rime docs

server/pipeline/pipeline-task.mdx, server/utilities/opentelemetry.mdx
Updates docs to match pipecat-ai/pipecat#1992
=> Update otel attributes in PipelineTask and OpenTelemetry docs

mint.json, server/services/llm/sambanova.mdx, server/services/stt/sambanova.mdx, server/services/supported-services.mdx
Add docs for PR: https://github.com/pipecat-ai/pipecat/pull/2020
=> Add sambanova llm and stt integration docs

server/services/s2s/openai.mdx
Docs for: https://github.com/pipecat-ai/pipecat/pull/2038
=> Update docs for OpenAI Realtime: new model 2025-06-03

guides/fundamentals/function-calling.mdx, server/services/llm/google-vertex.mdx, server/services/llm/sambanova.mdx
NOTE: this PR should only be merged once a Pipecat version containing [the corresponding change](https://github.com/pipecat-ai/pipecat/pull/2051) has been published.
=> Document direct functions

server/services/stt/speechmatics.mdx
Documentation for the Speechmatics STT module.
=> Speechmatics STT

guides/fundamentals/user-input-muting.mdx, server/utilities/filters/stt-mute.mdx
Updating docs with the latest recommendation on STTMuteFilter placement.
=> Update STTMuteFilter docs with new placement recommendation

mint.json, server/utilities/runner/guide.mdx, server/utilities/runner/transport-utils.mdx
Docs for https://github.com/pipecat-ai/pipecat/pull/2269
=> Add runner docs

server/services/supported-services.mdx, server/services/tts/inworld.mdx
Superseding https://github.com/pipecat-ai/docs/pull/290
=> Add InworldTTSService docs

getting-started/client-server.mdx, mint.json
- Add Inworld to nav
- Change nav title for client/server example
=> Small fixes to docs

client/js/introduction.mdx
Fixes [#2459](https://github.com/pipecat-ai/pipecat/issues/2459)
=> fix: update reference to onTrackStarted

client/ios/introduction.mdx, client/ios/migration-guide.mdx, client/ios/transports/daily.mdx, client/js/migration-guide.mdx, client/migration-guide.mdx, client/react/migration-guide.mdx, docs.json
=> iOS migration guide.

docs.json, guides/fundamentals/ivr.mdx, server/services/llm/anthropic.mdx, server/utilities/extensions/ivr.mdx
Docs for https://github.com/pipecat-ai/pipecat/pull/2529
Do not merge until IVR navigation is released.
=> Add IVR docs

deployment/pipecat-cloud/guides/container-registries/aws-ecr.mdx
Updated AWS ECR credentials format and added scheduling instructions.
=> Revise AWS ECR secret configuration and scheduling
